# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sojug/golang:latest
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
fullnameOverride: "my-app"



podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  name: my-app
  type: LoadBalancer
  port: 80
  

ingress:
  enabled: true
  name: golang-app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: golang-demo.ml
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: example-app-tls
     hosts:
       - golang-demo.ml

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}


certificate:
  enabled: true
  name: example-app
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
    dnsNames: golang-demo.ml
  secretName: example-app-tls

issuer:
  enabled: true
  name: letsencrypt-cluster-issuer
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sojugeorgek@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
  class: nginx

